name: web_socket_support_platform_interface
description: A common platform interface for the web_socket_support plugin.
homepage: https://github.com/sharpbitstudio/flutter-plugins/tree/master/web_socket_support/web_socket_support_platform_interface
version: 0.1.4

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.2
  meta: ^1.2.4
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.9.0

