name: web_socket_support_platform_interface
description: A common platform interface for the web_socket_support plugin.
homepage: https://github.com/sharpbitstudio/flutter-plugins/tree/master/web_socket_support/web_socket_support_platform_interface
version: 0.2.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.1
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  pedantic: ^1.11.0

