name: web_socket_support_platform_interface
description: A common platform interface for the web_socket_support plugin.
repository: https://github.com/sharpbitstudio/flutter-plugins
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.1
  meta: ^1.0.5
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.9.0

