name: web_socket_support
description: Flutter plugin for utilising OkHttp websocket implementation on Android. Supports
  text and binary messages. Works even when app is in background or when screen is locked.
homepage: https://github.com/sharpbitstudio/flutter-plugins/tree/master/web_socket_support/web_socket_support
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_support_platform_interface: ^0.1.5
  meta: ^1.2.4
  async: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.3
  pedantic: ^1.9.2

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: tech.sharpbitstudio.web_socket_support
        pluginClass: WebSocketSupportPlugin
