name: Build

on:
  push:
  pull_request:
  schedule:
    # runs the CI every 1st day in month at 10AM
    - cron: "0 10 1 * *"

jobs:
  flutter:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:${{matrix.channel}}

    strategy:
      matrix:
        channel:
          # - dev
          # - beta
          - stable

    steps:
      - uses: actions/checkout@v2

      - name: Execute build script
        run: sh .github/scripts/ci.sh